/* ------------------------------------------------------------------ */
/* UI copy, per language. Add a new language by adding a new key here  */
/* (and a matching entry in answers.js).                               */
/* ------------------------------------------------------------------ */

export const STRINGS = {
  fr: {
    dir: "ltr",
    subtitle: "Assistant officiel d'information citoyenne",
    welcomeTitle: "Comment puis-je vous aider aujourd'hui ?",
    welcomeMessage:
      "Posez votre question en langage courant. Je m'appuie uniquement sur des sources officielles.",
    suggested: [
      "Comment renouveler ma CNIE (carte d'identité) ?",
      "Quels documents pour une demande de passeport biométrique ?",
      "Comment obtenir un extrait d'acte de naissance ?",
      "Comment obtenir un certificat de résidence ?",
      "Comment immatriculer un véhicule (carte grise) ?",
    ],
    placeholder: "Écrivez votre question…",
    send: "Envoyer",
    stop: "Arrêter la génération",
    attach: "Joindre un fichier",
    maxFiles: "Maximum 5 fichiers, 10 Mo chacun.",
    recordTooltip: "Message vocal",
    micPermissionError: "Accès au microphone refusé. Autorisez-le dans les paramètres de votre navigateur.",
    micUnsupported: "L'enregistrement vocal n'est pas pris en charge par ce navigateur.",
    uploading: "Envoi…",
    sendingVoice: "Envoi du message vocal…",
    sourcesTitle: "Sources",
    citizenGenericLabel: "Recherche et vérification en cours…",
    agentErrorGeneric: "Une erreur est survenue lors du traitement de votre question. Veuillez réessayer.",
    rateLimitedMessage: "Trop de requêtes envoyées. Veuillez patienter une minute avant de réessayer.",
    ttsUnavailable: "Service audio momentanément indisponible.",
    ttsEmptyError: "Impossible de générer l'audio, veuillez réessayer.",
    ttsGenericError: "Une erreur est survenue lors de la génération audio.",
    emptyRecording: "Aucun son n'a été enregistré.",
    voicePrepError: "Impossible de préparer l'enregistrement.",
    emptyTranscription: "Aucune transcription n'a pu être produite.",
    asrUnavailable: "Service de transcription momentanément indisponible.",
    networkError: "Erreur réseau lors de la transcription audio.",
    invalidAsrResponse: "Réponse de transcription invalide.",
    recording: "Enregistrement en cours",
    cancel: "Annuler",
    sendRecording: "Envoyer l'enregistrement",
    listen: "Écouter",
    stopListening: "Arrêter l'écoute",
    copy: "Copier",
    copied: "Copié",
    helpful: "Utile",
    notHelpful: "Pas utile",
    report: "Signaler un problème",
    share: "Partager",
    citizenMode: "Mode citoyen",
    detailedMode: "Mode détaillé",
    displayMode: "Affichage du traitement",
    disclaimer:
      "Assistant automatisé. Les réponses peuvent contenir des erreurs — vérifiez les informations essentielles auprès des services concernés.",
    settingsTitle: "Paramètres d'affichage",
    newConversation: "Nouvelle conversation",
    institutionLabel: "Nom de l'institution",
    subtitleLabel: "Sous-titre de l'assistant",
    colorLabel: "Couleur principale",
    languageLabel: "Langue",
    close: "Fermer",
    seeMore: "En savoir plus",
    seeLess: "Réduire",
    toolPanelTitle: "Détail du traitement",
    inputsOutputs: "Entrées / Sorties",
    status: { running: "en cours", done: "terminé" },
    steps: [
      { label: "Recherche dans les sources officielles…", name: "recherche_sources_officielles", summary: "3 documents pertinents trouvés sur le portail officiel" },
      { label: "Vérification de la réglementation en vigueur…", name: "verification_reglementation", summary: "Réglementation 2026 confirmée, aucune mise à jour récente" },
      { label: "Préparation de votre réponse…", name: "preparation_reponse", summary: "Synthèse rédigée à partir de 3 sources vérifiées" },
    ],
  },
  en: {
    dir: "ltr",
    subtitle: "Official citizen information assistant",
    welcomeTitle: "How can I help you today?",
    welcomeMessage:
      "Ask your question in plain language. I rely only on official sources.",
    suggested: [
      "How do I renew my national ID card (CNIE)?",
      "What documents are needed for a biometric passport?",
      "How do I get a birth certificate extract?",
      "How do I get a certificate of residence?",
      "How do I register a vehicle (carte grise)?",
    ],
    placeholder: "Type your question…",
    send: "Send",
    stop: "Stop generating",
    attach: "Attach a file",
    maxFiles: "Maximum 5 files, 10 MB each.",
    recordTooltip: "Voice message",
    micPermissionError: "Microphone access denied. Please allow it in your browser settings.",
    micUnsupported: "Voice recording isn't supported in this browser.",
    uploading: "Uploading…",
    sendingVoice: "Sending voice message…",
    sourcesTitle: "Sources",
    citizenGenericLabel: "Searching and verifying…",
    agentErrorGeneric: "Something went wrong while processing your question. Please try again.",
    rateLimitedMessage: "Too many requests sent. Please wait a minute before trying again.",
    ttsUnavailable: "Audio service momentarily unavailable.",
    ttsEmptyError: "Unable to generate audio, please try again.",
    ttsGenericError: "Something went wrong while generating the audio.",
    emptyRecording: "No audio was recorded.",
    voicePrepError: "Could not prepare the recording.",
    emptyTranscription: "No transcription could be produced.",
    asrUnavailable: "Transcription service momentarily unavailable.",
    networkError: "Network error while transcribing audio.",
    invalidAsrResponse: "Invalid transcription response.",
    recording: "Recording",
    cancel: "Cancel",
    sendRecording: "Send recording",
    listen: "Listen",
    stopListening: "Stop listening",
    copy: "Copy",
    copied: "Copied",
    helpful: "Helpful",
    notHelpful: "Not helpful",
    report: "Report an issue",
    share: "Share",
    citizenMode: "Citizen mode",
    detailedMode: "Detailed mode",
    displayMode: "Processing display",
    disclaimer:
      "Automated assistant. Answers may contain errors — please verify essential information with the relevant department.",
    settingsTitle: "Display settings",
    newConversation: "New conversation",
    institutionLabel: "Institution name",
    subtitleLabel: "Assistant subtitle",
    colorLabel: "Primary colour",
    languageLabel: "Language",
    close: "Close",
    seeMore: "Learn more",
    seeLess: "Show less",
    toolPanelTitle: "Processing details",
    inputsOutputs: "Inputs / Outputs",
    status: { running: "running", done: "done" },
    steps: [
      { label: "Searching official sources…", name: "official_sources_search", summary: "3 relevant documents found on the official portal" },
      { label: "Checking current regulations…", name: "regulation_check", summary: "2026 regulation confirmed, no recent update" },
      { label: "Preparing your answer…", name: "answer_preparation", summary: "Summary drafted from 3 verified sources" },
    ],
  },
  ar: {
    dir: "rtl",
    subtitle: "المساعد الرسمي لمعلومات المواطنين",
    welcomeTitle: "كيف يمكنني مساعدتك اليوم؟",
    welcomeMessage: "اطرح سؤالك بلغة بسيطة. أعتمد فقط على مصادر رسمية.",
    suggested: [
      "كيف أجدد بطاقتي الوطنية للتعريف الإلكترونية (CNIE)؟",
      "ما هي الوثائق المطلوبة لجواز السفر البيومتري؟",
      "كيف أحصل على نسخة من عقد الازدياد؟",
      "كيف أحصل على شهادة السكنى؟",
      "كيف أسجل سيارة (البطاقة الرمادية)؟",
    ],
    placeholder: "اكتب سؤالك…",
    send: "إرسال",
    stop: "إيقاف التوليد",
    attach: "إرفاق ملف",
    maxFiles: "5 ملفات كحد أقصى، 10 ميغابايت لكل ملف.",
    recordTooltip: "رسالة صوتية",
    micPermissionError: "تم رفض الوصول إلى الميكروفون. يرجى السماح به في إعدادات المتصفح.",
    micUnsupported: "تسجيل الصوت غير متوفر في هذا المتصفح.",
    uploading: "جارٍ الإرسال…",
    sendingVoice: "جارٍ إرسال الرسالة الصوتية…",
    sourcesTitle: "المصادر",
    citizenGenericLabel: "جارٍ البحث والتحقق…",
    agentErrorGeneric: "حدث خطأ أثناء معالجة سؤالك. يرجى المحاولة مرة أخرى.",
    rateLimitedMessage: "تم إرسال عدد كبير جدًا من الطلبات. يرجى الانتظار دقيقة قبل المحاولة مرة أخرى.",
    ttsUnavailable: "خدمة الصوت غير متوفرة مؤقتًا.",
    ttsEmptyError: "تعذر إنشاء الصوت، يرجى المحاولة مرة أخرى.",
    ttsGenericError: "حدث خطأ أثناء إنشاء الصوت.",
    emptyRecording: "لم يتم تسجيل أي صوت.",
    voicePrepError: "تعذر تجهيز التسجيل.",
    emptyTranscription: "تعذر إنتاج أي نص من التسجيل.",
    asrUnavailable: "خدمة تحويل الصوت إلى نص غير متوفرة مؤقتًا.",
    networkError: "خطأ في الشبكة أثناء تحويل الصوت إلى نص.",
    invalidAsrResponse: "استجابة غير صالحة من خدمة تحويل الصوت.",
    recording: "جارٍ التسجيل",
    cancel: "إلغاء",
    sendRecording: "إرسال التسجيل",
    listen: "استماع",
    stopListening: "إيقاف الاستماع",
    copy: "نسخ",
    copied: "تم النسخ",
    helpful: "مفيد",
    notHelpful: "غير مفيد",
    report: "الإبلاغ عن مشكلة",
    share: "مشاركة",
    citizenMode: "وضع المواطن",
    detailedMode: "الوضع التفصيلي",
    displayMode: "عرض المعالجة",
    disclaimer:
      "مساعد آلي. قد تحتوي الإجابات على أخطاء — يرجى التحقق من المعلومات الأساسية لدى الجهة المعنية.",
    settingsTitle: "إعدادات العرض",
    newConversation: "محادثة جديدة",
    institutionLabel: "اسم المؤسسة",
    subtitleLabel: "العنوان الفرعي للمساعد",
    colorLabel: "اللون الأساسي",
    languageLabel: "اللغة",
    close: "إغلاق",
    seeMore: "معرفة المزيد",
    seeLess: "عرض أقل",
    toolPanelTitle: "تفاصيل المعالجة",
    inputsOutputs: "المدخلات / المخرجات",
    status: { running: "قيد التنفيذ", done: "منتهي" },
    steps: [
      { label: "البحث في المصادر الرسمية…", name: "بحث_المصادر_الرسمية", summary: "تم العثور على 3 وثائق ذات صلة في البوابة الرسمية" },
      { label: "التحقق من التنظيم الساري…", name: "التحقق_من_التنظيم", summary: "تم تأكيد تنظيم 2026، لا يوجد تحديث حديث" },
      { label: "تحضير إجابتك…", name: "تحضير_الإجابة", summary: "تم إعداد ملخص من 3 مصادر موثقة" },
    ],
  },
};