/* ------------------------------------------------------------------ */
/* UI copy, per language. Add a new language by adding a new key here  */
/* (and a matching entry in answers.js).                               */
/* ------------------------------------------------------------------ */

export const STRINGS = {
  fr: {
    dir: "ltr",
    subtitle: "Assistant officiel d'information citoyenne",
    welcomeTitle: "Comment puis-je vous aider aujourd'hui ?",
    welcomeMessage:
      "Posez votre question en langage courant. Je m'appuie uniquement sur des sources officielles.",
    suggested: [
      "Comment renouveler ma CNIE (carte d'identité) ?",
      "Quels documents pour une demande de passeport biométrique ?",
      "Comment obtenir un extrait d'acte de naissance ?",
      "Comment obtenir un certificat de résidence ?",
      "Comment immatriculer un véhicule (carte grise) ?",
    ],
    placeholder: "Écrivez votre question…",
    send: "Envoyer",
    stop: "Arrêter la génération",
    attach: "Joindre un fichier",
    maxFiles: "Maximum 5 fichiers, 10 Mo chacun.",
    recordTooltip: "Message vocal",
    micPermissionError: "Accès au microphone refusé. Autorisez-le dans les paramètres de votre navigateur.",
    micUnsupported: "L'enregistrement vocal n'est pas pris en charge par ce navigateur.",
    recordingTooLong: "L'enregistrement est limité à 25 secondes. Veuillez réessayer.",
    uploading: "Envoi…",
    sendingVoice: "Envoi du message vocal…",
    sourcesTitle: "Sources",
    citizenGenericLabel: "Recherche et vérification en cours…",
    agentErrorGeneric: "Une erreur est survenue lors du traitement de votre question. Veuillez réessayer.",
    rateLimitedMessage: "Trop de requêtes envoyées. Veuillez patienter une minute avant de réessayer.",
    ttsUnavailable: "Service audio momentanément indisponible.",
    ttsEmptyError: "Impossible de générer l'audio, veuillez réessayer.",
    ttsGenericError: "Une erreur est survenue lors de la génération audio.",
    emptyRecording: "Aucun son n'a été enregistré.",
    voicePrepError: "Impossible de préparer l'enregistrement.",
    emptyTranscription: "Aucune transcription n'a pu être produite.",
    asrUnavailable: "Service de transcription momentanément indisponible.",
    networkError: "Erreur réseau lors de la transcription audio.",
    invalidAsrResponse: "Réponse de transcription invalide.",
    recording: "Enregistrement en cours",
    cancel: "Annuler",
    sendRecording: "Envoyer l'enregistrement",
    listen: "Écouter",
    stopListening: "Arrêter l'écoute",
    copy: "Copier",
    copied: "Copié",
    helpful: "Utile",
    notHelpful: "Pas utile",
    report: "Signaler un problème",
    share: "Partager",
    citizenMode: "Mode citoyen",
    detailedMode: "Mode détaillé",
    displayMode: "Affichage du traitement",
    processingComplete: "Traitement terminé",
    disclaimer:
      "Assistant automatisé. Les réponses peuvent contenir des erreurs — vérifiez les informations essentielles auprès des services concernés.",
    settingsTitle: "Paramètres d'affichage",
    newConversation: "Nouvelle conversation",
    confirmResetTitle: "Démarrer une nouvelle conversation ?",
    confirmResetBody: "Cela effacera votre conversation actuelle. Voulez-vous continuer ?",
    confirmResetConfirm: "Confirmer",
    confirmResetCancel: "Annuler",
    institutionLabel: "Nom de l'institution",
    subtitleLabel: "Sous-titre de l'assistant",
    colorLabel: "Couleur principale",
    contrastWarning: "Contraste insuffisant : le texte de l'en-tête peut être difficile à lire avec cette couleur.",
    assistantIconLabel: "Icône de l'assistant (URL)",
    assistantIconPlaceholder: "https://exemple.gov.ma/icone-assistant.png",
    languageLabel: "Langue",
    themeLabel: "Thème",
    themeLight: "Clair",
    themeDark: "Sombre",
    close: "Fermer",
    seeMore: "En savoir plus",
    seeLess: "Réduire",
    toolPanelTitle: "Détail du traitement",
    thinkingLabel: "Réflexion en cours…",
    toolStepFailedLabel: "Cette étape a rencontré une difficulté — poursuite du traitement…",
    toolQueryTermsShow: "Afficher les termes de recherche",
    toolQueryTermsHide: "Masquer les termes de recherche",
    toolOutputShow: "Afficher le résultat",
    toolOutputHide: "Masquer le résultat",
    toolNameFallback: "Vérification d'une source officielle…",
    stepsCompletedLabel: "étapes effectuées",
    toolCallsLabel: "étapes terminées",
    toolNames: {
      super_hybrid_search: "Recherche dans les sources officielles",
      get_items_by_indices: "Récupération des informations détaillées",
      let_us_deepdive_chunkwise: "Analyse approfondie des contenus",
    },
    status: { running: "en cours", done: "terminé" },
    steps: [
      { label: "Recherche dans les sources officielles…", name: "recherche_sources_officielles", summary: "3 documents pertinents trouvés sur le portail officiel",
        args: '{"first_or":["renouvellement carte grise","documents nécessaires"],"mandatories":["carte grise"],"semantic_queries":["comment renouveler une carte grise au Maroc","pièces à fournir pour la carte grise"]}',
        output: "--- Résultat Semantique 1 ---\nchunk_index: 12\nproc_title: Renouvellement de la carte grise\nadministration: Ministère de l'Équipement et de l'Eau\nthematic: Transport et véhicules\nsubthematic: Immatriculation\nlink: https://www.mtpnet.gov.ma/informationnel/fr/thematique/renouvellement-carte-grise\n\n--- Résultat Semantique 2 ---\nchunk_index: 27\nproc_title: Pièces justificatives — véhicule d'occasion\nadministration: DGSN\nthematic: Documents administratifs\nlink: https://www.dgsn.gov.ma/informationnel/fr/thematique/pieces-vehicule-occasion" },
      { label: "Vérification de la réglementation en vigueur…", name: "verification_reglementation", summary: "Réglementation 2026 confirmée, aucune mise à jour récente",
        args: '{"first_or":["réglementation 2026","délai de validité"],"semantic_queries":["dernière mise à jour réglementation carte grise"]}',
        output: "--- Résultat Semantique 1 ---\nchunk_index: 41\nproc_title: Réglementation en vigueur — janvier 2026\nadministration: Ministère de l'Équipement et de l'Eau\nthematic: Réglementation\ndelays: 15 jours\nlink: https://www.mtpnet.gov.ma/informationnel/fr/thematique/reglementation-2026" },
      { label: "Préparation de votre réponse…", name: "preparation_reponse", summary: "Synthèse rédigée à partir de 3 sources vérifiées",
        args: '{"mandatories":["synthèse citoyenne"]}',
        output: "--- Synthèse ---\nsources_utilisees: 3\nstatut: rédaction terminée" },
    ],
  },
  en: {
    dir: "ltr",
    subtitle: "Official citizen information assistant",
    welcomeTitle: "How can I help you today?",
    welcomeMessage:
      "Ask your question in plain language. I rely only on official sources.",
    suggested: [
      "How do I renew my national ID card (CNIE)?",
      "What documents are needed for a biometric passport?",
      "How do I get a birth certificate extract?",
      "How do I get a certificate of residence?",
      "How do I register a vehicle (carte grise)?",
    ],
    placeholder: "Type your question…",
    send: "Send",
    stop: "Stop generating",
    attach: "Attach a file",
    maxFiles: "Maximum 5 files, 10 MB each.",
    recordTooltip: "Voice message",
    micPermissionError: "Microphone access denied. Please allow it in your browser settings.",
    micUnsupported: "Voice recording isn't supported in this browser.",
    recordingTooLong: "Recordings are limited to 25 seconds. Please try again.",
    uploading: "Uploading…",
    sendingVoice: "Sending voice message…",
    sourcesTitle: "Sources",
    citizenGenericLabel: "Searching and verifying…",
    agentErrorGeneric: "Something went wrong while processing your question. Please try again.",
    rateLimitedMessage: "Too many requests sent. Please wait a minute before trying again.",
    ttsUnavailable: "Audio service momentarily unavailable.",
    ttsEmptyError: "Unable to generate audio, please try again.",
    ttsGenericError: "Something went wrong while generating the audio.",
    emptyRecording: "No audio was recorded.",
    voicePrepError: "Could not prepare the recording.",
    emptyTranscription: "No transcription could be produced.",
    asrUnavailable: "Transcription service momentarily unavailable.",
    networkError: "Network error while transcribing audio.",
    invalidAsrResponse: "Invalid transcription response.",
    recording: "Recording",
    cancel: "Cancel",
    sendRecording: "Send recording",
    listen: "Listen",
    stopListening: "Stop listening",
    copy: "Copy",
    copied: "Copied",
    helpful: "Helpful",
    notHelpful: "Not helpful",
    report: "Report an issue",
    share: "Share",
    citizenMode: "Citizen mode",
    detailedMode: "Detailed mode",
    displayMode: "Processing display",
    processingComplete: "Processing complete",
    disclaimer:
      "Automated assistant. Answers may contain errors — please verify essential information with the relevant department.",
    settingsTitle: "Display settings",
    newConversation: "New conversation",
    confirmResetTitle: "Start a new conversation?",
    confirmResetBody: "This will clear your current conversation. Do you want to continue?",
    confirmResetConfirm: "Confirm",
    confirmResetCancel: "Cancel",
    institutionLabel: "Institution name",
    subtitleLabel: "Assistant subtitle",
    colorLabel: "Primary colour",
    contrastWarning: "Not enough contrast: header text may be hard to read with this colour.",
    assistantIconLabel: "Assistant icon (URL)",
    assistantIconPlaceholder: "https://example.gov.ma/assistant-icon.png",
    languageLabel: "Language",
    themeLabel: "Theme",
    themeLight: "Light",
    themeDark: "Dark",
    close: "Close",
    seeMore: "Learn more",
    seeLess: "Show less",
    toolPanelTitle: "Processing details",
    thinkingLabel: "Thinking…",
    toolStepFailedLabel: "This step ran into an issue — continuing…",
    toolQueryTermsShow: "Show search terms",
    toolQueryTermsHide: "Hide search terms",
    toolOutputShow: "Show result",
    toolOutputHide: "Hide result",
    toolNameFallback: "Checking an official source…",
    stepsCompletedLabel: "steps completed",
    toolCallsLabel: "steps completed",
    toolNames: {
      super_hybrid_search: "Search official sources",
      get_items_by_indices: "Retrieve detailed information",
      let_us_deepdive_chunkwise: "Analyze source content",
    },
    status: { running: "running", done: "done" },
    steps: [
      { label: "Searching official sources…", name: "official_sources_search", summary: "3 relevant documents found on the official portal",
        args: '{"first_or":["vehicle registration renewal","required documents"],"mandatories":["registration card"],"semantic_queries":["how to renew a vehicle registration in Morocco","documents needed for registration card"]}',
        output: "--- Semantic Result 1 ---\nchunk_index: 12\nproc_title: Vehicle registration renewal\nadministration: Ministry of Equipment and Water\nthematic: Transport and vehicles\nsubthematic: Registration\nlink: https://www.mtpnet.gov.ma/informationnel/en/thematic/registration-renewal\n\n--- Semantic Result 2 ---\nchunk_index: 27\nproc_title: Supporting documents — used vehicle\nadministration: DGSN\nthematic: Administrative documents\nlink: https://www.dgsn.gov.ma/informationnel/en/thematic/used-vehicle-documents" },
      { label: "Checking current regulations…", name: "regulation_check", summary: "2026 regulation confirmed, no recent update",
        args: '{"first_or":["2026 regulation","validity period"],"semantic_queries":["latest update to vehicle registration regulation"]}',
        output: "--- Semantic Result 1 ---\nchunk_index: 41\nproc_title: Regulation in force — January 2026\nadministration: Ministry of Equipment and Water\nthematic: Regulation\ndelays: 15 days\nlink: https://www.mtpnet.gov.ma/informationnel/en/thematic/regulation-2026" },
      { label: "Preparing your answer…", name: "answer_preparation", summary: "Summary drafted from 3 verified sources",
        args: '{"mandatories":["citizen summary"]}',
        output: "--- Summary ---\nsources_used: 3\nstatus: drafting complete" },
    ],
  },
  ar: {
    dir: "rtl",
    subtitle: "المساعد الرسمي لمعلومات المواطنين",
    welcomeTitle: "كيف يمكنني مساعدتك اليوم؟",
    welcomeMessage: "اطرح سؤالك بلغة بسيطة. أعتمد فقط على مصادر رسمية.",
    suggested: [
      "كيف أجدد بطاقتي الوطنية للتعريف الإلكترونية (CNIE)؟",
      "ما هي الوثائق المطلوبة لجواز السفر البيومتري؟",
      "كيف أحصل على نسخة من عقد الازدياد؟",
      "كيف أحصل على شهادة السكنى؟",
      "كيف أسجل سيارة (البطاقة الرمادية)؟",
    ],
    placeholder: "اكتب سؤالك…",
    send: "إرسال",
    stop: "إيقاف التوليد",
    attach: "إرفاق ملف",
    maxFiles: "5 ملفات كحد أقصى، 10 ميغابايت لكل ملف.",
    recordTooltip: "رسالة صوتية",
    micPermissionError: "تم رفض الوصول إلى الميكروفون. يرجى السماح به في إعدادات المتصفح.",
    micUnsupported: "تسجيل الصوت غير متوفر في هذا المتصفح.",
    recordingTooLong: "مدة التسجيل محدودة في 25 ثانية. يرجى المحاولة مرة أخرى.",
    uploading: "جارٍ الإرسال…",
    sendingVoice: "جارٍ إرسال الرسالة الصوتية…",
    sourcesTitle: "المصادر",
    citizenGenericLabel: "جارٍ البحث والتحقق…",
    agentErrorGeneric: "حدث خطأ أثناء معالجة سؤالك. يرجى المحاولة مرة أخرى.",
    rateLimitedMessage: "تم إرسال عدد كبير جدًا من الطلبات. يرجى الانتظار دقيقة قبل المحاولة مرة أخرى.",
    ttsUnavailable: "خدمة الصوت غير متوفرة مؤقتًا.",
    ttsEmptyError: "تعذر إنشاء الصوت، يرجى المحاولة مرة أخرى.",
    ttsGenericError: "حدث خطأ أثناء إنشاء الصوت.",
    emptyRecording: "لم يتم تسجيل أي صوت.",
    voicePrepError: "تعذر تجهيز التسجيل.",
    emptyTranscription: "تعذر إنتاج أي نص من التسجيل.",
    asrUnavailable: "خدمة تحويل الصوت إلى نص غير متوفرة مؤقتًا.",
    networkError: "خطأ في الشبكة أثناء تحويل الصوت إلى نص.",
    invalidAsrResponse: "استجابة غير صالحة من خدمة تحويل الصوت.",
    recording: "جارٍ التسجيل",
    cancel: "إلغاء",
    sendRecording: "إرسال التسجيل",
    listen: "استماع",
    stopListening: "إيقاف الاستماع",
    copy: "نسخ",
    copied: "تم النسخ",
    helpful: "مفيد",
    notHelpful: "غير مفيد",
    report: "الإبلاغ عن مشكلة",
    share: "مشاركة",
    citizenMode: "وضع المواطن",
    detailedMode: "الوضع التفصيلي",
    displayMode: "عرض المعالجة",
    processingComplete: "اكتملت المعالجة",
    disclaimer:
      "مساعد آلي. قد تحتوي الإجابات على أخطاء — يرجى التحقق من المعلومات الأساسية لدى الجهة المعنية.",
    settingsTitle: "إعدادات العرض",
    newConversation: "محادثة جديدة",
    confirmResetTitle: "بدء محادثة جديدة؟",
    confirmResetBody: "سيؤدي هذا إلى مسح محادثتك الحالية. هل تريد المتابعة؟",
    confirmResetConfirm: "تأكيد",
    confirmResetCancel: "إلغاء",
    institutionLabel: "اسم المؤسسة",
    subtitleLabel: "العنوان الفرعي للمساعد",
    colorLabel: "اللون الأساسي",
    contrastWarning: "تباين غير كافٍ: قد يكون نص الترويسة صعب القراءة مع هذا اللون.",
    assistantIconLabel: "أيقونة المساعد (رابط)",
    assistantIconPlaceholder: "https://exemple.gov.ma/icone-assistant.png",
    languageLabel: "اللغة",
    themeLabel: "المظهر",
    themeLight: "فاتح",
    themeDark: "داكن",
    close: "إغلاق",
    seeMore: "معرفة المزيد",
    seeLess: "عرض أقل",
    toolPanelTitle: "تفاصيل المعالجة",
    thinkingLabel: "جارٍ التفكير…",
    toolStepFailedLabel: "واجهت هذه الخطوة صعوبة — متابعة المعالجة…",
    toolQueryTermsShow: "إظهار مصطلحات البحث",
    toolQueryTermsHide: "إخفاء مصطلحات البحث",
    toolOutputShow: "إظهار النتيجة",
    toolOutputHide: "إخفاء النتيجة",
    toolNameFallback: "التحقق من مصدر رسمي…",
    stepsCompletedLabel: "خطوات منجزة",
    toolCallsLabel: "خطوات منجزة",
    toolNames: {
      super_hybrid_search: "البحث في المصادر الرسمية",
      get_items_by_indices: "جلب المعلومات التفصيلية",
      let_us_deepdive_chunkwise: "التحليل المعمق للمحتوى",
    },
    status: { running: "قيد التنفيذ", done: "منتهي" },
    steps: [
      { label: "البحث في المصادر الرسمية…", name: "بحث_المصادر_الرسمية", summary: "تم العثور على 3 وثائق ذات صلة في البوابة الرسمية",
        args: '{"first_or":["تجديد البطاقة الرمادية","الوثائق المطلوبة"],"mandatories":["البطاقة الرمادية"],"semantic_queries":["كيفية تجديد البطاقة الرمادية بالمغرب","الوثائق اللازمة لتجديد البطاقة الرمادية"]}',
        output: "--- نتيجة دلالية 1 ---\nchunk_index: 12\nproc_title: تجديد البطاقة الرمادية\nadministration: وزارة التجهيز والماء\nthematic: النقل والمركبات\nsubthematic: التسجيل\nlink: https://www.mtpnet.gov.ma/informationnel/ar/thematique/tajdid-bataqa-ramadia\n\n--- نتيجة دلالية 2 ---\nchunk_index: 27\nproc_title: الوثائق الثبوتية — سيارة مستعملة\nadministration: المديرية العامة للأمن الوطني\nthematic: الوثائق الإدارية\nlink: https://www.dgsn.gov.ma/informationnel/ar/thematique/watha2iq-sayara-mostaamala" },
      { label: "التحقق من التنظيم الساري…", name: "التحقق_من_التنظيم", summary: "تم تأكيد تنظيم 2026، لا يوجد تحديث حديث",
        args: '{"first_or":["تنظيم 2026","مدة الصلاحية"],"semantic_queries":["آخر تحديث لتنظيم البطاقة الرمادية"]}',
        output: "--- نتيجة دلالية 1 ---\nchunk_index: 41\nproc_title: التنظيم الساري — يناير 2026\nadministration: وزارة التجهيز والماء\nthematic: التنظيم\ndelays: 15 يومًا\nlink: https://www.mtpnet.gov.ma/informationnel/ar/thematique/tanzim-2026" },
      { label: "تحضير إجابتك…", name: "تحضير_الإجابة", summary: "تم إعداد ملخص من 3 مصادر موثقة",
        args: '{"mandatories":["ملخص للمواطن"]}',
        output: "--- ملخص ---\nsources_used: 3\nstatus: اكتملت الصياغة" },
    ],
  },
};
